# Generated by Django 5.2 on 2025-04-29 16:58

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rooms.models.generate_room_code, max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('host', models.CharField(max_length=100)),
                ('players_count', models.IntegerField(default=0)),
            ],
        ),
    ]
