# Generated by Django 5.2 on 2025-04-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('created', 'Комната создана'), ('in_progress', 'Игра идет'), ('finished', 'Игра закончена')], default='created', max_length=20),
        ),
    ]
