# Generated by Django 5.2 on 2025-04-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
