# Generated by Django 5.2 on 2025-05-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_player_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city_name',
            field=models.CharField(default='Без города', max_length=100),
            preserve_default=False,
        ),
    ]
