# Generated by Django 5.2 on 2025-05-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_player_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_room', to='rooms.player'),
        ),
    ]
