# Generated by Django 5.2 on 2025-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_deckcardentry_is_played_crossroad'),
        ('rooms', '0006_room_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(blank=True, related_name='in_hand_of_players', to='cards.deckcardentry'),
        ),
    ]
