# Generated by Django 5.2 on 2025-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_player_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание хода'), ('set_cards', 'Набор карт'), ('playing_cards', 'Розыгрыш карт')], default='waiting', max_length=20),
        ),
    ]
