# Generated by Django 5.2 on 2025-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_deckcardentry_is_played_crossroad'),
        ('rooms', '0008_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='played_cards',
            field=models.ManyToManyField(blank=True, related_name='played_in_city_of_players', to='cards.deckcardentry'),
        ),
    ]
