# Generated by Django 5.2 on 2025-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_player_played_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='crusade_points',
            field=models.IntegerField(default=0),
        ),
    ]
