# Generated by Django 5.2 on 2025-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_crusade_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='count_relics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='count_relics',
            field=models.IntegerField(default=3),
        ),
    ]
