# Generated by Django 5.2 on 2025-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('court', 'Придворные'), ('priest', 'Священники'), ('peasant', 'Крестьяне'), ('universal', 'Любое сословие'), ('epidemic', 'Эпидемии')], max_length=50)),
                ('victory_points', models.IntegerField()),
                ('immunity', models.IntegerField(blank=True, null=True)),
                ('crusade_points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('quantity_in_deck', models.IntegerField(default=1)),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
