# Generated by Django 5.2 on 2025-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEpidemic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('death_count', models.PositiveIntegerField()),
                ('effect', models.TextField()),
            ],
        ),
    ]
