# Generated by Django 5.2 on 2025-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardepidemic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardepidemic',
            name='image_name',
            field=models.CharField(default='leprosy', max_length=100),
            preserve_default=False,
        ),
    ]
