# Generated by Django 5.2 on 2025-05-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardepidemic_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardepidemic',
            name='hotbed_image',
            field=models.CharField(default='hotbed_leprosy', max_length=100),
            preserve_default=False,
        ),
    ]
