# Generated by Django 5.2 on 2025-05-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardepidemic_hotbed_image'),
        ('rooms', '0005_player_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='cards.DeckCard', to='cards.card'),
        ),
        migrations.CreateModel(
            name='DeckEpidemicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
                ('epidemic_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardepidemic')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='epidemic_cards',
            field=models.ManyToManyField(through='cards.DeckEpidemicCard', to='cards.cardepidemic'),
        ),
    ]
