# Generated by Django 5.2 on 2025-05-01 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_deck_deckcard_deck_cards_deckepidemiccard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='deckepidemiccard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='deckepidemiccard',
            name='epidemic_card',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='epidemic_cards',
        ),
        migrations.CreateModel(
            name='DeckCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('regular', 'Обычная'), ('epidemic', 'Эпидемия')], max_length=20)),
                ('card_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cards.deck')),
            ],
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
        migrations.DeleteModel(
            name='DeckEpidemicCard',
        ),
    ]
