# Generated by Django 5.2 on 2025-05-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_deck_cards_remove_deckepidemiccard_deck_and_more'),
        ('rooms', '0006_room_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcardentry',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Crossroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_card1', to='cards.deckcardentry')),
                ('card2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_card2', to='cards.deckcardentry')),
                ('card3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_card3', to='cards.deckcardentry')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad', to='rooms.room')),
            ],
        ),
    ]
