# Generated by Django 5.2 on 2025-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_deckcardentry_is_played_crossroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcardentry',
            name='card_group_in_deck',
            field=models.CharField(choices=[('court', 'Придворные'), ('priest', 'Священники'), ('peasant', 'Крестьяне'), ('universal', 'Любое сословие'), ('epidemic', 'Эпидемии')], default='universal', max_length=20),
            preserve_default=False,
        ),
    ]
