# Generated by Django 5.2 on 2025-05-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_deckcardentry_card_group_in_deck'),
        ('rooms', '0009_player_played_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEpidemic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_count', models.PositiveIntegerField(default=1)),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_city', to='rooms.player')),
                ('epidemic_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardepidemic')),
                ('hotbed_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotbed_city', to='rooms.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_epidemics', to='rooms.room')),
            ],
        ),
    ]
