# Generated by Django 5.2 on 2025-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_activeepidemic'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='play_only_in_own_city',
            field=models.BooleanField(default=False),
        ),
    ]
