# Generated by Django 5.2 on 2025-05-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_play_only_in_own_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_women',
            field=models.BooleanField(default=False),
        ),
    ]
